In [1]:
#
#
#   Python implementation of TTH "Toy Tetragraph Hash
#       problem 2.7 in Computer Security Textbook
#
#

import sys
import numpy as np

VALIDLETTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

#   define a TTH Hashing class with variables and methods

class TTHHash():

    def __init__(self, str):
        self.hash = np.array([0,0,0,0])
        self.data = None
        self.numBlocks = 0
        self.str = str.upper()


        #   Remove non-alphabetic characters and convert string to array of numbers from 0 to 25

        cleanString = ''.join([char for char in self.str if char in VALIDLETTERS])
        print (cleanString)
        numbers = []
        numbers = [ord(cleanString[i])-65 for i in range(len(cleanString))]
        self.data = np.array(numbers)
        print (self.data, "\n\n")

        # pad with zeros to make blocks of 16, then shape into nx4x4 array

        padLength = (16 - len(self.data) % 16) % 16
        self.data = np.pad(self.data, [0,padLength], mode='constant')
        self.numBlocks = int((len(self.data)-1) / 16) + 1
        self.data.shape = (self.numBlocks,4,4)
        print ("Data to be hashed: \n", self.data, "\n\n")

    # Method to convert hash array back to alpha string

    def alphaHash(self):
        s = ""
        for c in self.hash:
            s += chr(c+65)
        return s

    # Method to calculate hash for a single block

    def cookHash(self, i):

        # round 1: add columns mod 26, add to hash mod 26
        aSum = np.mod (self.data[i].sum(axis=0), 26)
        self.hash = np.mod( (self.hash + aSum), 26)

        # round 2:  rotate or flip, add columns mod 26, add to hash mod 26
        x = self.data[i]
        x[0] = np.roll(x[0], -1)
        x[1] = np.roll(x[1], -2)
        x[2] = np.roll(x[2], -3)
        x[3] = np.flip(x[3], axis=0)
        aSum = np.mod(self.data[i].sum(axis=0), 26)
        self.hash = np.mod((self.hash + aSum), 26)


#   MAIN routine

if __name__ == '__main__':
    str = "Big Bad Wolf vs Goldilocks: the fight of the century!"
    h = TTHHash(str)
    for i in range(h.numBlocks):
        h.cookHash(i)

    print ("number of blocks: ", h.numBlocks)
    print ("numeric hash: ", h.hash)
    print ()
    print ("alpha hash: ", h.alphaHash())
    exit()

BIGBADWOLFVSGOLDILOCKSTHEFIGHTOFTHECENTURY
[ 1  8  6  1  0  3 22 14 11  5 21 18  6 14 11  3  8 11 14  2 10 18 19  7
  4  5  8  6  7 19 14  5 19  7  4  2  4 13 19 20 17 24] 


Data to be hashed: 
 [[[ 1  8  6  1]
  [ 0  3 22 14]
  [11  5 21 18]
  [ 6 14 11  3]]

 [[ 8 11 14  2]
  [10 18 19  7]
  [ 4  5  8  6]
  [ 7 19 14  5]]

 [[19  7  4  2]
  [ 4 13 19 20]
  [17 24  0  0]
  [ 0  0  0  0]]] 


number of blocks:  3
numeric hash:  [23 15 16  0]

alpha hash:  XPQA
